# Model Architecture
model:
  lstm_units: [128, 64]
  dense_units: [32]
  dropout_rate: 0.3
  sequence_length: 60
  batch_size: 32
  epochs: 100

# Training Configuration
training:
  optimizer: adam
  learning_rate: 0.001
  loss: mse
  validation_split: 0.2
  early_stopping:
    patience: 10
    monitor: val_loss
    mode: min
  model_checkpoint:
    filepath: "models/checkpoints/model_{epoch:02d}_{val_loss:.4f}.h5"
    save_best_only: true
    monitor: val_loss

# Data Processing
data:
  features:
    price:
      - open
      - high
      - low
      - close
      - volume
    technical:
      moving_averages: [5, 10, 20, 50]
      rsi: true
      macd: true
      bollinger_bands: true
      vwap: true
    market:
      - vix
      - sector_performance
  
  preprocessing:
    price_normalization: standard_scaler
    volume_transform: log
    sequence_padding: zero
    train_test_split: 0.8
    validation_split: 0.2

# Evaluation
evaluation:
  metrics:
    - mse
    - mae
    - rmse
    - r2_score
  visualization:
    plot_predictions: true
    plot_loss: true
    plot_metrics: true
